[options]
input = './slhaFiles/T2_example.slha'
checkmateFolder = './CheckMATE2'
ncpu = 30
cleanUp = False
#useSLHAxsecs = {"T2" : (2212,2212,-1000001,1000001)}
#xsecUnit = PB

[CheckMateParameters]
Analyses = atlas_2010_14293
InvisiblePIDs = 1000022
QuietMode = True
OutputExists = 'overwrite'
OutputDirectory =  './data/T2'
TotalResultFileColumns: analysis,sr,robs,rexp,s,ds,eff,signalsumofweights,s95obs,robscons,rexpcons
WritePythiaEvents = True
WriteDelphesEvents = True

[CheckMateProcess]
Name = "T2"
MGcommand = "import model MSSM_SLHA2\n define sq = ul cl dl sl ur cr dr sr\n define asq = ul~ cl~ dl~ sl~ ur~ cr~ dr~ sr~ \n generate p p > sq asq;"
MaxEvents = 25000
MGparam = ${CheckMateParameters:SLHAfile}
#XSectErr = '20.0 %'
